name:                keelung-compiler
version:             0.1.0.0
github:              "btq-ag/keelung-compiler"
license:             BSD3
author:              "Ting-GIan LUA"
maintainer:          "ty.lai@btq.li"
copyright:           "2022 BTQ AG"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/btq-ag/keelung-compiler#readme>

dependencies:
- base >= 4.7 && < 5
- array 
- bytestring 
- cereal
- mtl
- containers
- semirings
- galois-field
- random
- keelung 
- optparse-applicative

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Werror=incomplete-patterns
    - -fno-warn-orphans

executables:
  keelungc:
    main:                Main.hs
    source-dirs:        
      - app/
      - src/
      - examples/
    dependencies:
    - keelung-compiler

    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror=incomplete-patterns
      - -fno-warn-orphans



tests:
  keelung-test:
    main:                Main.hs
    source-dirs:        
      - test/
      - examples/
    dependencies:
    - keelung-compiler
    - hspec


    ghc-options:
      - -Wall
      - -Werror=incomplete-patterns
      - -fno-warn-orphans

benchmarks:
  keelung-bench:
    main: Main.hs
    source-dirs:
      - src
      - benchmark/
      - examples/
    dependencies:
      - keelung-compiler
      - snarkl
      - criterion 		>=1.0

    ghc-options:
      - -Wall
      - -Werror=incomplete-patterns
      - -fno-warn-orphans
