name:                keelung
version:             0.1.0.0
github:              "githubuser/keelung"
license:             BSD3
author:              "Ting-GIan LUA"
maintainer:          "ty.lai@btq.li"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/keelung#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers

library:
  source-dirs: src

executables:
  keelung-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - keelung

tests:
  keelung-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - keelung

ghc-options:
  - -Wall
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Werror=incomplete-patterns
  - -fno-warn-orphans

